/** ~~~~~~~~~ Wrapper class to hold the value of Blended revenue calculation variables ~~~~~~~~ **/ 
public class CalculateBlendedWrapper {
    	
   	//Variables
	public Decimal recognizedAmount;
	public Decimal deferredAmount;
	public Decimal outStandingBalance;
	public String msg ;
	public Decimal actualDeferred;
	public Decimal actualCatDifference;
	
	//Constructer
	public CalculateBlendedWrapper() {
	}
}