/** 
 *	Description		:	Trigger helper for TriggerRevRecProductCategory
 *
 *	Craeted By		:	William Feeheley
 *
 *	Created Date	:	08/03/2017
 *
 *	Version			:	V_1.0
 *
 *	Revision Log	:	V_1.0 - Created
**/
public without sharing class RevRecProductCategoryTriggerHelper {
	
	/** 
	 *	@description	:	This method is used to populate converetdd amount.
	**/
	public static void setConveretedValues(List<RevRecProductRuleCategory__c> newCatgs) {
		 
		 
	}
}